rules:
  no-trailing-whitespace:
    - 0
    - include: false
  final-newline:
    - 0
    - include: false
  indentation:
    - 0
    - include: false
  space-after-colon:
    - 0
    - include: false
  one-declaration-per-line:
    - 0
    - include: false
  property-sort-order:
    - 0
    - include: false
  no-css-comments:
    - 0
    - include: false
  empty-line-between-blocks:
    - 0
    - include: false
  no-vendor-prefixes:
    - 0
    - include: false
  space-after-comma:
    - 0
    - include: false